.TH Rust 1.21 Docker image
.PP
This container image includes Rust 1.21 as a
S2I
\[la]https://github.com/openshift/source-to-image\[ra] base image for your Rust
1.21 applications. It is based on CentOS builder images and installs Rust from
EPEL
\[la]https://fedoraproject.org/wiki/EPEL\[ra]\&.

.SH Description
.PP
Rust 1.21 available as docker container is a base plaform for building and
running varios Rust $RUST\_VERSION applications and frameworks.

.SH Usage.IP \(bu 2
TODO

.SH Environment variables
.PP
To set these environment variables, you can place them as a key value pair
into a \fB\fC\&.s2i/environment\fR file inside your source code repository.
.IP \(bu 2
DISABLE\_RELEASE

.PP
Set this variable to a non\-empty value to inhibit the release build process
  in cargo. This will force cargo to build the application with a debug
  profile.
